### PR TITLE
loop to get all the stacks (limited to 120 on each pass)

### PR DESCRIPTION
**Pull request by jrgm**
Yo @gene1wood, can you r=?

### CODE REVIEW

**Comment by jrgm** [comment]
Yo, @gene1wood.

**Comment by ckolos** [comment]
@gene1wood is out for a bit... Something popped up.

**Comment by jrgm** [comment]
@ckolos thanks. Did not know that. Congratulations @gene1wood. Just ignore this.

**Comment by jrgm** [comment]
Hey @gene1wood. Can you have at look at this fix for [aws-tools/bind_dns.py](https://github.com/mozilla/identity-ops/blob/master/aws-tools/bind_dns.py) and  [aws-tools/gh.py](https://github.com/mozilla/identity-ops/blob/master/aws-tools/gh.py)

**Comment by ckolos** [comment]
reviewing for gene1wood. This looks fine. Merging.

**Pull request merged**
